GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWVydGNhbiIsImlhdCI6MTYzMzIwMDE1MywiZXhwIjoxNjMzMjAwMTgzfQ.Ld-qDGdQfiYbJOwzEroBVLaSgEQ4FG89p6PlC9RaoQQ

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWVydGNhbiIsImlhdCI6MTYzMzIwMDI0NX0.4537OSrm6EU4ilfwZnBcmAGqbjDtLKuwJipy_HPqUS8"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWVydGNhbiIsImlhdCI6MTYzMzIwMDI0NX0.4537OSrm6EU4ilfwZnBcmAGqbjDtLKuwJipy_HPqUS8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Mertcan"
}